## Import of libraries

In [2]:
import pandas as pd

## Visualization of the data

In [3]:
df = pd.read_csv('../data/raw/PixarMovies.csv')
df

,Year Released,Movie,Length,RT Score,IMDB Score,Metacritic Score,Opening Weekend,Worldwide Gross,Domestic Gross,Adjusted Domestic Gross,International Gross,Domestic %,International %,Production Budget,Oscars Nominated,Oscars Won
0,1995,Toy Story,81,100,8.3,92,29.14,362.0,191.8,356.21,170.2,52.98%,47.02%,30,3.0,0.0
1,1998,A Bug's Life,96,92,7.2,77,33.26,363.4,162.8,277.18,200.6,44.80%,55.20%,45,1.0,0.0
2,1999,Toy Story 2,92,100,7.9,88,57.39,485.0,245.9,388.43,239.2,50.70%,49.32%,90,1.0,0.0
3,2001,"Monsters, Inc.",90,96,8.1,78,62.58,528.8,255.9,366.12,272.9,48.39%,51.61%,115,3.0,1.0
4,2003,Finding Nemo,104,99,8.2,90,70.25,895.6,339.7,457.46,555.9,37.93%,62.07%,94,4.0,1.0
5,2004,The Incredibles,115,97,8.0,90,70.47,631.4,261.4,341.28,370.0,41.40%,58.60%,92,4.0,2.0
6,2006,Cars,116,74,7.2,73,60.12,462.0,244.1,302.59,217.9,52.84%,47.16%,70,2.0,0.0
7,2007,Ratatouille,111,96,8.0,96,47.00,623.7,206.4,243.65,417.3,33.09%,66.91%,150,5.0,1.0
8,2008,WALL-E,97,96,8.4,94,63.10,521.3,223.8,253.11,297.5,42.93%,57.07%,180,6.0,1.0
9,2009,Up,96,98,8.3,88,68.11,731.3,293.0,318.90,438.3,40.07%,59.93%,175,5.0,2.0
10,2010,Toy Story 3,103,99,8.4,92,110.31,1063.2,415.0,423.88,648.2,39.03%,60.97%,200,5.0,2.0
11,2011,Cars 2,113,39,6.3,57,109.00,559.9,191.5,194.43,368.4,34.20%,65.80%,200,0.0,0.0
12,2012,Brave,100,78,7.2,69,66.30,539.0,237.3,243.39,301.7,44.03%,55.97%,185,1.0,1.0
13,2013,Monsters University,107,78,7.4,65,82.43,743.6,268.5,269.59,475.1,36.11%,63.89%,200,0.0,0.0
14,2015,Inside Out,102,98,8.8,93,90.40,677.1,340.5,340.50,336.6,50.29%,49.71%,175,NaN,NaN

## Looking for issues with the data

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year Released            15 non-null     int64
 1   Movie                    15 non-null     object
 2   Length                   15 non-null     int64
 3   RT Score                 15 non-null     int64
 4   IMDB Score               15 non-null     float64
 5   Metacritic Score         15 non-null     int64
 6   Opening Weekend          15 non-null     float64
 7   Worldwide Gross          15 non-null     float64
 8   Domestic Gross           15 non-null     float64
 9   Adjusted Domestic Gross  15 non-null     float64
 10  International Gross      15 non-null     float64
 11  Domestic %               15 non-null     object
 12  International %          15 non-null     object
 13  Production Budget        15 non-null     int64
 14  Oscars Nominated         14 non-null     float64
 15  Oscars Won               14 non-null     float64
dtypes: float64(8), int64(5), object(3)
memory usage: 2.0+ KB

## Changing the Datatype of Domestic and International % from object to float

In [5]:
df['Domestic %'] = df['Domestic %'].str.replace('%', '').astype(float)
df['International %'] = df['International %'].str.replace('%', '').astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year Released            15 non-null     int64
 1   Movie                    15 non-null     object
 2   Length                   15 non-null     int64
 3   RT Score                 15 non-null     int64
 4   IMDB Score               15 non-null     float64
 5   Metacritic Score         15 non-null     int64
 6   Opening Weekend          15 non-null     float64
 7   Worldwide Gross          15 non-null     float64
 8   Domestic Gross           15 non-null     float64
 9   Adjusted Domestic Gross  15 non-null     float64
 10  International Gross      15 non-null     float64
 11  Domestic %               15 non-null     float64
 12  International %          15 non-null     float64
 13  Production Budget        15 non-null     int64
 14  Oscars Nominated         14 non-null     float64
 15  Oscars Won               14 non-null     float64
dtypes: float64(10), int64(5), object(1)
memory usage: 2.0+ KB

## Imputing the missing values

In this case, I insert the values because I know them

In [6]:
df.loc[14, 'Oscars Nominated'] = 2
df.loc[14, 'Oscars Won'] = 1
df

,Year Released,Movie,Length,RT Score,IMDB Score,Metacritic Score,Opening Weekend,Worldwide Gross,Domestic Gross,Adjusted Domestic Gross,International Gross,Domestic %,International %,Production Budget,Oscars Nominated,Oscars Won
0,1995,Toy Story,81,100,8.3,92,29.14,362.0,191.8,356.21,170.2,52.98,47.02,30,3.0,0.0
1,1998,A Bug's Life,96,92,7.2,77,33.26,363.4,162.8,277.18,200.6,44.80,55.20,45,1.0,0.0
2,1999,Toy Story 2,92,100,7.9,88,57.39,485.0,245.9,388.43,239.2,50.70,49.32,90,1.0,0.0
3,2001,"Monsters, Inc.",90,96,8.1,78,62.58,528.8,255.9,366.12,272.9,48.39,51.61,115,3.0,1.0
4,2003,Finding Nemo,104,99,8.2,90,70.25,895.6,339.7,457.46,555.9,37.93,62.07,94,4.0,1.0
5,2004,The Incredibles,115,97,8.0,90,70.47,631.4,261.4,341.28,370.0,41.40,58.60,92,4.0,2.0
6,2006,Cars,116,74,7.2,73,60.12,462.0,244.1,302.59,217.9,52.84,47.16,70,2.0,0.0
7,2007,Ratatouille,111,96,8.0,96,47.00,623.7,206.4,243.65,417.3,33.09,66.91,150,5.0,1.0
8,2008,WALL-E,97,96,8.4,94,63.10,521.3,223.8,253.11,297.5,42.93,57.07,180,6.0,1.0
9,2009,Up,96,98,8.3,88,68.11,731.3,293.0,318.90,438.3,40.07,59.93,175,5.0,2.0
10,2010,Toy Story 3,103,99,8.4,92,110.31,1063.2,415.0,423.88,648.2,39.03,60.97,200,5.0,2.0
11,2011,Cars 2,113,39,6.3,57,109.00,559.9,191.5,194.43,368.4,34.20,65.80,200,0.0,0.0
12,2012,Brave,100,78,7.2,69,66.30,539.0,237.3,243.39,301.7,44.03,55.97,185,1.0,1.0
13,2013,Monsters University,107,78,7.4,65,82.43,743.6,268.5,269.59,475.1,36.11,63.89,200,0.0,0.0
14,2015,Inside Out,102,98,8.8,93,90.40,677.1,340.5,340.50,336.6,50.29,49.71,175,2.0,1.0

## Correcting the data of Inside Out

In [7]:
df.loc[14] = [2015, 'Inside Out', 95, 98, 8.1, 94, 90.44, 858.85, 356.92, 356.92, 501.93, 41.6, 58.4, 175, 2, 1]
df

,Year Released,Movie,Length,RT Score,IMDB Score,Metacritic Score,Opening Weekend,Worldwide Gross,Domestic Gross,Adjusted Domestic Gross,International Gross,Domestic %,International %,Production Budget,Oscars Nominated,Oscars Won
0,1995,Toy Story,81,100,8.3,92,29.14,362.00,191.80,356.21,170.20,52.98,47.02,30,3.0,0.0
1,1998,A Bug's Life,96,92,7.2,77,33.26,363.40,162.80,277.18,200.60,44.80,55.20,45,1.0,0.0
2,1999,Toy Story 2,92,100,7.9,88,57.39,485.00,245.90,388.43,239.20,50.70,49.32,90,1.0,0.0
3,2001,"Monsters, Inc.",90,96,8.1,78,62.58,528.80,255.90,366.12,272.90,48.39,51.61,115,3.0,1.0
4,2003,Finding Nemo,104,99,8.2,90,70.25,895.60,339.70,457.46,555.90,37.93,62.07,94,4.0,1.0
5,2004,The Incredibles,115,97,8.0,90,70.47,631.40,261.40,341.28,370.00,41.40,58.60,92,4.0,2.0
6,2006,Cars,116,74,7.2,73,60.12,462.00,244.10,302.59,217.90,52.84,47.16,70,2.0,0.0
7,2007,Ratatouille,111,96,8.0,96,47.00,623.70,206.40,243.65,417.30,33.09,66.91,150,5.0,1.0
8,2008,WALL-E,97,96,8.4,94,63.10,521.30,223.80,253.11,297.50,42.93,57.07,180,6.0,1.0
9,2009,Up,96,98,8.3,88,68.11,731.30,293.00,318.90,438.30,40.07,59.93,175,5.0,2.0
10,2010,Toy Story 3,103,99,8.4,92,110.31,1063.20,415.00,423.88,648.20,39.03,60.97,200,5.0,2.0
11,2011,Cars 2,113,39,6.3,57,109.00,559.90,191.50,194.43,368.40,34.20,65.80,200,0.0,0.0
12,2012,Brave,100,78,7.2,69,66.30,539.00,237.30,243.39,301.70,44.03,55.97,185,1.0,1.0
13,2013,Monsters University,107,78,7.4,65,82.43,743.60,268.50,269.59,475.10,36.11,63.89,200,0.0,0.0
14,2015,Inside Out,95,98,8.1,94,90.44,858.85,356.92,356.92,501.93,41.60,58.40,175,2.0,1.0

## Saving the data to csv

In [8]:
df.to_csv('../data/processed/PixarMovies.csv', index=False)